version: '2.2'
services:
  prometheus-singleton:
    image: prom/prometheus:v2.12.0
    container_name: prometheus-singleton
    volumes:
      - ./data:/prometheus-data
    ports:
      - 9090:9090
    networks:
      - docker-net

networks:
  docker-net:
    external: true